[phases.setup]
nixPkgs = ["nodejs_18", "python311", "python311Packages.pip", "libGL", "libGLU", "glib"]

[phases.install]
cmds = [
  "(cd node-backend && npm install)",
  "pip install --break-system-packages -r backend/requirements.txt"
]

[start]
cmd = "cd node-backend && node server.js"
