[phases.setup]
nixPkgs = ["nodejs_18", "python311", "python311Packages.pip", "libGL", "libGLU", "glib", "zlib"]

[phases.install]
cmds = [
  "(cd node-backend && npm install)",
  "pip install --break-system-packages -r backend/requirements.txt"
]

[start]
cmd = "cd node-backend && node server.js"

[variables]
LD_LIBRARY_PATH = "/nix/store/*-zlib-*/lib:$LD_LIBRARY_PATH"
