services:
  - type: web
    name: deepfake-detection-backend
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: "bash build.sh"
    startCommand: "cd node-backend && node server.js"
    envVars:
      - key: PORT
        value: 8080
