services:
  - type: web
    name: deepfake-detection-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r backend/requirements.txt && cd node-backend && npm install"
    startCommand: "cd node-backend && node server.js"
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.11.0
