[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "libGL", "libGLU", "glib"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r ../backend/requirements.txt"
]

[start]
cmd = "node server.js"
